
//    --------------------------------------------------------------------
//
//    This file is part of Luna.
//
//    LUNA is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Luna is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Luna. If not, see <http://www.gnu.org/licenses/>.
//
//    Please see LICENSE.txt for more details.
//
//    --------------------------------------------------------------------

// POPS-CODA: second-stage LightGBM rescoring for POPS sleep staging
//
// CODA uses POPS stage-1 posterior probabilities plus temporal/contextual
// features to train a second LightGBM model.  It supports both 5-state
// (W R N1 N2 N3) and 3-state (W R NR) modes with the fixed class ordering
// W=0, R=1, N1=2, N2=3, N3=4.
//
// Training note: CODA should be trained on *out-of-sample* POPS stage-1
// predictions (e.g. validation-set predictions from the POPS training run).
// Training on stage-1 predictions generated by a model that was itself
// trained on the same subjects will yield unrealistically clean posteriors.
//
// Flagged/bad epochs are retained in the feature matrix with all-NaN features
// and are excluded from rolling/global/cumulative calculations.

#ifdef HAS_LGBM

#ifndef __LUNA_POPS_CODA_H__
#define __LUNA_POPS_CODA_H__

#include "lgbm/lgbm.h"
#include "stats/Eigen/Dense"

#include <vector>
#include <string>
#include <set>

struct edf_t;

class pops_coda_t {
 public:

  struct options_t {
    int    context_epochs       = 20;   // half-window in epochs (10 min at 30 s)
    double row_duration_sec     = 30.0; // spacing between posterior rows
    int    min_subject_contiguous_epochs = 0; // require at least this many contiguous valid epochs to include a subject
    std::vector<int> min_stage_minutes = {5};  // per-stage minimums in W,R,N1,N2,N3 order; size-1 applies to all
    double min_stage1_kappa     = 0.5;  // require stage-1 hard calls vs PRIOR to reach at least this kappa
    int    random_validation_subjects = 0; // additionally sample this many good subjects into validation
    double lambda               = 2.0;  // denominator smoothing for rel_elapsed features
    std::vector<double> class_weights;  // per-class training weights in W,R,N1,N2,N3 / W,R,NR order
    bool   include_future       = true; // future-context features (offline mode)
    bool   include_global       = true; // recording-level posterior totals / fractions
    bool   include_prev_next    = true; // immediate prev/next epoch posteriors
    bool   include_quantiles    = true; // past/future posterior quantiles
    bool   include_hard_props   = true; // past/future hard-call stage proportions
    bool   include_entropy_margin = true; // top_prob, second_prob, margin, entropy
    bool   require_all_stages   = true; // require every effective stage to be observed at least once
    bool   broad_stage_qc      = false; // group N1+N2+N3 as NREM for require_all_stages / min_stage_minutes checks
    bool   three_state          = false; // 3-state (W R NR) vs 5-state (W R N1 N2 N3)
    bool   do_SHAP             = false; // emit CODA SHAP values during prediction
  } opt;

  pops_coda_t() {}

  // ---------------------------------------------------------------------------
  // Training workflow
  //   1. Call accumulate() for each training subject (out-of-sample posteriors)
  //   2. Call train_model() to fit the LightGBM booster
  //   3. Call save() to write the model + feature-name list
  // ---------------------------------------------------------------------------

  // Accumulate one subject's data into the training set.
  // P:  ne × n_classes stage-1 posteriors (5 or 3 columns, already in W R N1 N2 N3 order)
  // S:  ne manual stage labels (POPS_WAKE/REM/N1/N2/N3/UNKNOWN)
  // E:  ne epoch indices (0-based, increasing)
  // subject_id is only used for logging; return value is the number of rows added.
  int accumulate( const Eigen::MatrixXd & P ,
                  const std::vector<int> & S ,
                  const std::vector<int> & E ,
                  const std::string & subject_id = "" );

  // Train CODA from a plain-text posteriors file (destrat POPS -r E format).
  // Columns required: ID  E  PP_W  PP_R  PP_N1+PP_N2+PP_N3 (5-state) or PP_NR (3-state)  PRIOR
  // E is 1-based; PRIOR is a stage label string (W/R/N1/N2/N3/NR/? ...)
  // Calls accumulate() per subject then train_model().
  void train_from_posteriors_file( const std::string & filename ,
                                   const std::string & config_file = "." ,
                                   int n_iterations = 200 );

  // Predict CODA outputs from a plain-text posteriors file.
  // Uses the same format as train_from_posteriors_file(), except PRIOR is optional.
  // Optional START/STOP columns, if present, are copied through to epoch-level output.
  void predict_from_posteriors_file( const std::string & filename );

  // Load a file of subject IDs to hold out for LightGBM validation.
  // Uses the same plain-text one-ID-per-token format as POPS validation= / hold-outs=.
  void load_validation_ids( const std::string & filename );

  // Fit the CODA LightGBM model on accumulated data.
  // config_file: path to an LightGBM config file, or "." for CODA defaults
  void train_model( const std::string & config_file = "." ,
                    int n_iterations = 200 );

  // ---------------------------------------------------------------------------
  // Save / load
  // ---------------------------------------------------------------------------

  void save( const std::string & f );  // writes f (model) + f+".fnames"
  void load( const std::string & f );  // reads  f (model) + f+".fnames"

  bool has_model() const { return lgbm.has_booster; }

  // ---------------------------------------------------------------------------
  // Prediction
  //   Called after pops_indiv_t::predict() has populated P/E/PS/S.
  //   Writes CODA outputs at epoch level under MODEL=CODA stratum.
  // ---------------------------------------------------------------------------

  // P:          ne × n_classes POPS stage-1 posteriors
  // E:          ne epoch indices (into recording)
  // flagged:    ne  – flagged[e] = true if epoch is bad (POPS_UNKNOWN or NaN in P)
  // ne_total:   total recording epochs (including skipped ones not in E)
  // has_staging: whether manual labels are present
  // S:          ne manual labels (used to write PRIOR field)
  // pedf:       pointer to EDF (for clock times), may be NULL
  void predict( const Eigen::MatrixXd & P ,
                const std::vector<int> & E ,
                const std::vector<bool> & flagged ,
                int ne_total ,
                bool has_staging ,
                const std::vector<int> & S ,
                edf_t * pedf ,
                const std::vector<std::string> * start = NULL ,
                const std::vector<std::string> * stop = NULL ,
                bool emit_stage1 = true );

  // Matrix-only rescoring path for callers that want CODA posteriors without
  // writing the standard epoch-level MDL=CODA outputs.
  Eigen::MatrixXd rescore( const Eigen::MatrixXd & P ,
                           const std::vector<int> & E ,
                           const std::vector<bool> & flagged );

  // Build the feature-name list for the current options (deterministic)
  std::vector<std::string> feature_names() const;
  int n_features() const { return (int)feature_names().size(); }
  static int scale_context_epochs( int context_30s_epochs , double row_duration_sec );

 private:

  lgbm_t lgbm;

  // Accumulated training / validation rows and labels (buffered as row vectors for efficiency)
  std::vector<Eigen::VectorXd> X_train_rows;
  std::vector<int>             S_train;
  std::vector<Eigen::VectorXd> X_valid_rows;
  std::vector<int>             S_valid;
  std::set<std::string>        holdouts;

  // Feature names as loaded from the .fnames file (used to validate at predict time)
  std::vector<std::string> loaded_fnames;

  // ---------------------------------------------------------------------------
  // Core feature computation
  // ---------------------------------------------------------------------------

  // Builds X (ne × n_features) with all-NaN rows for flagged epochs.
  // P must already be in effective-ns-column form (3 or 5 depending on opt.three_state).
  void make_features( const Eigen::MatrixXd & P ,
                      const std::vector<int> & E ,
                      const std::vector<bool> & flagged ,
                      Eigen::MatrixXd & X ,
                      std::vector<std::string> & fnames ) const;

  // If opt.three_state and P has 5 columns: collapse N1+N2+N3 → NR, renormalise.
  // Otherwise returns P unchanged.
  Eigen::MatrixXd adapt_posteriors( const Eigen::MatrixXd & P ) const;

  // Validate shape and approximate unit-sum of posteriors; normalise if needed.
  // Returns the (possibly normalised) matrix, or halts on hard errors.
  Eigen::MatrixXd validate_and_normalise( const Eigen::MatrixXd & P ) const;

  // Number of effective classes after adaptation
  int n_classes() const { return opt.three_state ? 3 : 5; }

  // Stage labels in W R N1 N2 N3 / W R NR order
  std::vector<std::string> stage_labels() const;

  // Default LightGBM params for CODA (shallow, regularised trees)
  std::string coda_default_params( int num_class , int n_iterations ) const;

  // Quantile of a (possibly unsorted) vector; ignores NaN
  static double coda_quantile( std::vector<double> v , double q );

  // Report class-specific SHAP values using CODA feature names.
  void SHAP( const Eigen::MatrixXd & X ,
             const std::vector<std::string> & fnames ,
             const std::vector<int> & E ,
             const std::vector<bool> & flagged );
};

#endif
#endif
